import shutil
import sys
import time
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

# FIXTURES: path to the test fixture directory containing sharp.jpg and blurry.jpg.
# These are small synthetic images generated by the fixture-creation script —
# no dependency on real photos from temp/.
FIXTURES = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _reset_server_conn():
    """
    Clear the module-level DB connection in server.py.

    server.py caches a single sqlite3 connection in `_conn` for the lifetime
    of the process. Between tests, we need to reset it so each test gets a
    fresh connection pointing at its own tmp_path DB — otherwise tests share
    state and bleed into each other.
    """
    import server
    server._conn = None


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def isolated_db(tmp_path, monkeypatch):
    """
    Redirect server._DB_PATH to a per-test temp DB for every test in this file.

    autouse=True means this runs automatically — no test needs to explicitly
    request it. Ensures no test touches ~/.triage-keepers/cache.db.

    tmp_path: pytest built-in fixture providing a unique temp directory per test.
    monkeypatch: pytest built-in for safe attribute overrides that auto-revert
                 after the test completes.
    """
    import server
    monkeypatch.setattr(server, "_DB_PATH", tmp_path / "test_cache.db")
    _reset_server_conn()
    yield
    _reset_server_conn()


@pytest.fixture
def jpg_dir(tmp_path):
    """
    Create a temp directory with 3 JPEG files copied from sharp.jpg fixture.

    Used by index_folder tests to avoid depending on the real temp/ folder,
    which has 175 files and a real mtime history. Three files is enough to
    test first-run, second-run, and single-file-change scenarios.

    Returns: Path to the temp directory containing photo_00.jpg, photo_01.jpg,
             photo_02.jpg.
    """
    for i in range(3):
        shutil.copy(FIXTURES / "sharp.jpg", tmp_path / f"photo_{i:02d}.jpg")
    return tmp_path


# ---------------------------------------------------------------------------
# list_folders tests
# ---------------------------------------------------------------------------

def test_list_folders_returns_subdirs(tmp_path):
    """
    list_folders must return only directories, not files.

    Creates two subdirs (aaa, zzz) and one file (file.txt) inside tmp_path.
    Confirms the tool filters out files — important because Claude uses this
    list to navigate the photo library hierarchy; stale files in the list
    would confuse the agent.

    tmp_path: pytest temp dir — unique per test, auto-cleaned after.
    Expected output: result contains "aaa" and "zzz", does NOT contain "file.txt".
    """
    (tmp_path / "aaa").mkdir()
    (tmp_path / "zzz").mkdir()
    (tmp_path / "file.txt").write_text("x")

    from server import list_folders
    result = list_folders(str(tmp_path))
    names = [Path(p).name for p in result]

    assert "aaa" in names
    assert "zzz" in names
    assert "file.txt" not in names


def test_list_folders_sorted(tmp_path):
    """
    list_folders results must be alphabetically sorted.

    Creates three subdirs in non-alphabetical order (charlie, alpha, bravo).
    Claude reads folder lists top-to-bottom; unsorted output makes navigation
    harder and produces inconsistent agent behavior across runs.

    Expected output: names list equals its own sorted version.
    """
    (tmp_path / "charlie").mkdir()
    (tmp_path / "alpha").mkdir()
    (tmp_path / "bravo").mkdir()

    from server import list_folders
    result = list_folders(str(tmp_path))
    names = [Path(p).name for p in result]

    assert names == sorted(names)


def test_list_folders_bad_path():
    """
    list_folders must return [] for a nonexistent path, not raise an exception.

    The server must never crash on bad user input passed through Claude Desktop.
    An exception would kill the MCP server process and require a full Claude
    Desktop restart to recover.

    Expected output: empty list [].
    """
    from server import list_folders
    result = list_folders("/this/does/not/exist/anywhere")
    assert result == []


# ---------------------------------------------------------------------------
# index_folder tests
# ---------------------------------------------------------------------------

def test_index_folder_first_run(jpg_dir):
    """
    On a fresh DB, every JPG must be indexed (all cache misses).

    jpg_dir: fixture providing 3 JPEGs in a temp directory.
    indexed == total confirms the upsert path ran for every file.
    skipped == 0 confirms no false cache hits on an empty DB.

    Expected output: {"total": 3, "indexed": 3, "skipped": 0}
    """
    from server import index_folder
    result = index_folder(str(jpg_dir))

    assert result["total"] == 3
    assert result["indexed"] == 3
    assert result["skipped"] == 0


def test_index_folder_second_run(jpg_dir):
    """
    After indexing unchanged files, a second run must skip all of them.

    Calls index_folder twice on the same directory with no file changes between
    runs. skipped == total confirms needs_reindex correctly detects matching
    mtime+size and avoids redundant CV work (which will be expensive in evening 5).

    Expected output (second call): {"total": 3, "indexed": 0, "skipped": 3}
    """
    from server import index_folder
    index_folder(str(jpg_dir))          # first run — populates cache
    result = index_folder(str(jpg_dir)) # second run — all cache hits

    assert result["skipped"] == 3
    assert result["indexed"] == 0


def test_index_folder_detects_change(jpg_dir):
    """
    After touching one file (updating its mtime), only that file is re-indexed.

    time.sleep(0.01): ensures the OS records a different mtime after touch().
    Without the sleep, mtime resolution on some filesystems may not capture
    sub-millisecond changes.

    target: photo_00.jpg — the one file we modify.
    Expected output (third call): {"total": 3, "indexed": 1, "skipped": 2}
    """
    from server import index_folder
    index_folder(str(jpg_dir))

    target = jpg_dir / "photo_00.jpg"
    time.sleep(0.01)
    target.touch()

    result = index_folder(str(jpg_dir))
    assert result["indexed"] == 1
    assert result["skipped"] == 2


def test_index_folder_bad_path():
    """
    index_folder must return a dict with an "error" key for a nonexistent path.

    Same reasoning as test_list_folders_bad_path — must not crash the server.
    Returning {"error": "..."} lets Claude surface a readable message rather
    than receiving a silent failure or an exception traceback.

    Expected output: dict containing key "error".
    """
    from server import index_folder
    result = index_folder("/no/such/folder")

    assert "error" in result


# ---------------------------------------------------------------------------
# get_thumbnail tests
# ---------------------------------------------------------------------------

def test_get_thumbnail_returns_image():
    """
    get_thumbnail must return an MCPImage instance for a valid JPEG path.

    MCPImage is FastMCP's image wrapper — returning it causes the MCP SDK to
    serialize the image as base64 ImageContent, which Claude Desktop renders
    inline. Any other return type (str, dict, None) would break visual confirmation.

    Expected output: instance of mcp.server.fastmcp.Image.
    """
    from mcp.server.fastmcp import Image as MCPImage
    from server import get_thumbnail

    result = get_thumbnail(str(FIXTURES / "sharp.jpg"))
    assert isinstance(result, MCPImage)


def test_get_thumbnail_respects_size():
    """
    The returned thumbnail must fit within the requested size on both axes.

    size=32: deliberately small to make a visible size reduction from the
    64x64 fixture. Decodes the returned JPEG bytes with PIL to check actual
    pixel dimensions — confirms thumbnail() isn't being bypassed or the size
    param ignored.

    result.data: raw JPEG bytes stored on the MCPImage object.
    Expected output: width <= 32 AND height <= 32.
    """
    import io
    from PIL import Image as PILImage
    from server import get_thumbnail

    result = get_thumbnail(str(FIXTURES / "sharp.jpg"), size=32)
    img = PILImage.open(io.BytesIO(result.data))

    assert img.width <= 32
    assert img.height <= 32
