import shutil
import sys
import time
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

# FIXTURES: path to the test fixture directory containing sharp.jpg and blurry.jpg.
# These are small synthetic images generated by the fixture-creation script —
# no dependency on real photos from temp/.
FIXTURES = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _reset_server_conn():
    """
    Clear the module-level DB connection in server.py.

    server.py caches a single sqlite3 connection in `_conn` for the lifetime
    of the process. Between tests, we need to reset it so each test gets a
    fresh connection pointing at its own tmp_path DB — otherwise tests share
    state and bleed into each other.
    """
    import server
    server._conn = None


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def isolated_db(tmp_path, monkeypatch):
    """
    Redirect server._DB_PATH to a per-test temp DB for every test in this file.

    autouse=True means this runs automatically — no test needs to explicitly
    request it. Ensures no test touches ~/.triage-keepers/cache.db.

    tmp_path: pytest built-in fixture providing a unique temp directory per test.
    monkeypatch: pytest built-in for safe attribute overrides that auto-revert
                 after the test completes.
    """
    import server
    monkeypatch.setattr(server, "_DB_PATH", tmp_path / "test_cache.db")
    _reset_server_conn()
    yield
    _reset_server_conn()


@pytest.fixture
def jpg_dir(tmp_path):
    """
    Create a temp directory with 3 JPEG files copied from sharp.jpg fixture.

    Used by index_folder tests to avoid depending on the real temp/ folder,
    which has 175 files and a real mtime history. Three files is enough to
    test first-run, second-run, and single-file-change scenarios.

    Returns: Path to the temp directory containing photo_00.jpg, photo_01.jpg,
             photo_02.jpg.
    """
    for i in range(3):
        shutil.copy(FIXTURES / "sharp.jpg", tmp_path / f"photo_{i:02d}.jpg")
    return tmp_path


# ---------------------------------------------------------------------------
# list_folders tests
# ---------------------------------------------------------------------------

def test_list_folders_returns_subdirs(tmp_path):
    """
    list_folders must return only directories, not files.

    Creates two subdirs (aaa, zzz) and one file (file.txt) inside tmp_path.
    Confirms the tool filters out files — important because Claude uses this
    list to navigate the photo library hierarchy; stale files in the list
    would confuse the agent.

    tmp_path: pytest temp dir — unique per test, auto-cleaned after.
    Expected output: result contains "aaa" and "zzz", does NOT contain "file.txt".
    """
    (tmp_path / "aaa").mkdir()
    (tmp_path / "zzz").mkdir()
    (tmp_path / "file.txt").write_text("x")

    from server import list_folders
    result = list_folders(str(tmp_path))
    names = [Path(p).name for p in result]

    assert "aaa" in names
    assert "zzz" in names
    assert "file.txt" not in names


def test_list_folders_sorted(tmp_path):
    """
    list_folders results must be alphabetically sorted.

    Creates three subdirs in non-alphabetical order (charlie, alpha, bravo).
    Claude reads folder lists top-to-bottom; unsorted output makes navigation
    harder and produces inconsistent agent behavior across runs.

    Expected output: names list equals its own sorted version.
    """
    (tmp_path / "charlie").mkdir()
    (tmp_path / "alpha").mkdir()
    (tmp_path / "bravo").mkdir()

    from server import list_folders
    result = list_folders(str(tmp_path))
    names = [Path(p).name for p in result]

    assert names == sorted(names)


def test_list_folders_bad_path():
    """
    list_folders must return [] for a nonexistent path, not raise an exception.

    The server must never crash on bad user input passed through Claude Desktop.
    An exception would kill the MCP server process and require a full Claude
    Desktop restart to recover.

    Expected output: empty list [].
    """
    from server import list_folders
    result = list_folders("/this/does/not/exist/anywhere")
    assert result == []


# ---------------------------------------------------------------------------
# index_folder tests
# ---------------------------------------------------------------------------

def test_index_folder_first_run(jpg_dir):
    """
    On a fresh DB, every JPG must be indexed (all cache misses).

    jpg_dir: fixture providing 3 JPEGs in a temp directory.
    indexed == total confirms the upsert path ran for every file.
    skipped == 0 confirms no false cache hits on an empty DB.

    Expected output: {"total": 3, "indexed": 3, "skipped": 0}
    """
    from server import index_folder
    result = index_folder(str(jpg_dir))

    assert result["total"] == 3
    assert result["indexed"] == 3
    assert result["skipped"] == 0


def test_index_folder_second_run(jpg_dir):
    """
    After indexing unchanged files, a second run must skip all of them.

    Calls index_folder twice on the same directory with no file changes between
    runs. skipped == total confirms needs_reindex correctly detects matching
    mtime+size and avoids redundant CV work (which will be expensive in evening 5).

    Expected output (second call): {"total": 3, "indexed": 0, "skipped": 3}
    """
    from server import index_folder
    index_folder(str(jpg_dir))          # first run — populates cache
    result = index_folder(str(jpg_dir)) # second run — all cache hits

    assert result["skipped"] == 3
    assert result["indexed"] == 0


def test_index_folder_detects_change(jpg_dir):
    """
    After touching one file (updating its mtime), only that file is re-indexed.

    time.sleep(0.01): ensures the OS records a different mtime after touch().
    Without the sleep, mtime resolution on some filesystems may not capture
    sub-millisecond changes.

    target: photo_00.jpg — the one file we modify.
    Expected output (third call): {"total": 3, "indexed": 1, "skipped": 2}
    """
    from server import index_folder
    index_folder(str(jpg_dir))

    target = jpg_dir / "photo_00.jpg"
    time.sleep(0.01)
    target.touch()

    result = index_folder(str(jpg_dir))
    assert result["indexed"] == 1
    assert result["skipped"] == 2


def test_index_folder_bad_path():
    """
    index_folder must return a dict with an "error" key for a nonexistent path.

    Same reasoning as test_list_folders_bad_path — must not crash the server.
    Returning {"error": "..."} lets Claude surface a readable message rather
    than receiving a silent failure or an exception traceback.

    Expected output: dict containing key "error".
    """
    from server import index_folder
    result = index_folder("/no/such/folder")

    assert "error" in result


# ---------------------------------------------------------------------------
# get_thumbnail tests
# ---------------------------------------------------------------------------

def test_get_thumbnail_returns_image():
    """
    get_thumbnail must return an MCPImage instance for a valid JPEG path.

    MCPImage is FastMCP's image wrapper — returning it causes the MCP SDK to
    serialize the image as base64 ImageContent, which Claude Desktop renders
    inline. Any other return type (str, dict, None) would break visual confirmation.

    Expected output: instance of mcp.server.fastmcp.Image.
    """
    from mcp.server.fastmcp import Image as MCPImage
    from server import get_thumbnail

    result = get_thumbnail(str(FIXTURES / "sharp.jpg"))
    assert isinstance(result, MCPImage)


def test_get_thumbnail_respects_size():
    """
    The returned thumbnail must fit within the requested size on both axes.

    size=32: deliberately small to make a visible size reduction from the
    64x64 fixture. Decodes the returned JPEG bytes with PIL to check actual
    pixel dimensions — confirms thumbnail() isn't being bypassed or the size
    param ignored.

    result.data: raw JPEG bytes stored on the MCPImage object.
    Expected output: width <= 32 AND height <= 32.
    """
    import io
    from PIL import Image as PILImage
    from server import get_thumbnail

    result = get_thumbnail(str(FIXTURES / "sharp.jpg"), size=32)
    img = PILImage.open(io.BytesIO(result.data))

    assert img.width <= 32
    assert img.height <= 32


# ---------------------------------------------------------------------------
# find_orphans tests
# ---------------------------------------------------------------------------

def test_find_orphans_finds_unpaired_files(tmp_path):
    """
    find_orphans must detect RAW files without JPG pairs and vice versa.

    Creates paired (IMG_001.JPG + IMG_001.CR2) and orphan (IMG_002.JPG alone)
    files, then confirms the orphan is found in jpg_orphans list.

    Expected output: jpg_orphans contains IMG_002.JPG, jpg_count == 1.
    """
    from server import find_orphans

    (tmp_path / "IMG_001.JPG").write_text("jpg")
    (tmp_path / "IMG_001.CR2").write_text("raw")
    (tmp_path / "IMG_002.JPG").write_text("jpg")

    result = find_orphans(str(tmp_path), recursive=False)
    assert result["jpg_count"] == 1
    assert any("IMG_002.JPG" in path for path in result["jpg_orphans"])


def test_find_orphans_recursive_finds_in_subdirs(tmp_path):
    """
    find_orphans with recursive=True must find orphans in subdirectories.

    Creates nested structure: subdir/IMG_001.JPG (orphan), subdir/IMG_002.JPG (paired with CR2).
    Confirms orphan is found even though it's not in the root folder.

    Expected output: jpg_orphans contains subdir/IMG_001.JPG.
    """
    from server import find_orphans

    subdir = tmp_path / "2024"
    subdir.mkdir()
    (subdir / "IMG_001.JPG").write_text("jpg")
    (subdir / "IMG_002.JPG").write_text("jpg")
    (subdir / "IMG_002.CR2").write_text("raw")

    result = find_orphans(str(tmp_path), recursive=True)
    assert result["jpg_count"] == 1
    assert any("IMG_001.JPG" in path for path in result["jpg_orphans"])


# ---------------------------------------------------------------------------
# get_pair tests
# ---------------------------------------------------------------------------

def test_get_pair_finds_pairing(tmp_path):
    """
    get_pair must locate both JPG and RAW files with matching basenames.

    Creates IMG_001.JPG and IMG_001.CR2, then queries for IMG_001.JPG.
    Confirms status == "paired" and both paths are returned.

    Expected output: status == "paired", jpg and raw both not None.
    """
    from server import get_pair

    (tmp_path / "IMG_001.JPG").write_text("jpg")
    (tmp_path / "IMG_001.CR2").write_text("raw")

    result = get_pair("IMG_001.JPG", str(tmp_path))
    assert result["status"] == "paired"
    assert result["jpg"] is not None
    assert result["raw"] is not None


def test_get_pair_recursive_finds_in_subdirs(tmp_path):
    """
    get_pair with recursive=True must find paired files in subdirectories.

    Creates subdir/IMG_001.JPG and subdir/IMG_001.CR2, then queries from root folder.
    Confirms status == "paired" even though files are nested.

    Expected output: status == "paired" when recursive=True.
    """
    from server import get_pair

    subdir = tmp_path / "2024"
    subdir.mkdir()
    (subdir / "IMG_001.JPG").write_text("jpg")
    (subdir / "IMG_001.CR2").write_text("raw")

    result = get_pair("IMG_001.JPG", str(tmp_path), recursive=True)
    assert result["status"] == "paired"
    assert result["jpg"] is not None
    assert result["raw"] is not None


# ---------------------------------------------------------------------------
# assess_subject_sharpness tests
# ---------------------------------------------------------------------------

def test_assess_subject_sharpness_caches_on_second_call(jpg_dir):
    """
    assess_subject_sharpness must cache mtime/size to avoid infinite re-scoring.

    First call: cache miss, scores the photo, stores mtime+size in cache.
    Second call: cache hit, returns from cache without re-scoring.

    Without mtime/size (prior bug), needs_reindex would always return True,
    causing every call to re-score even unchanged files.

    Expected output: second call completes faster (returns from cache, skips CV).
    """
    import time
    from server import assess_subject_sharpness

    test_jpg = jpg_dir / "photo_00.jpg"

    start = time.time()
    result1 = assess_subject_sharpness(str(test_jpg))
    elapsed1 = time.time() - start

    start = time.time()
    result2 = assess_subject_sharpness(str(test_jpg))
    elapsed2 = time.time() - start

    assert result1["face_count"] == 0  # sharp.jpg has no faces
    assert result2["face_count"] == 0
    # Second call should be much faster (cache hit, no CV)
    # On a single 64x64 pixel image, CV takes ~0.1s; cache hit takes ~0.01s
    assert elapsed2 < elapsed1 * 0.5  # second call is at most half as slow


# ---------------------------------------------------------------------------
# find_no_subject tests
# ---------------------------------------------------------------------------

def test_find_no_subject_with_limit(jpg_dir):
    """
    find_no_subject must respect limit parameter and not return all rows.

    Indexes 3 photos (all no-face), then queries with limit=1.
    Confirms only 1 result is returned despite 3 photos in cache.

    Expected output: results list has length 1, count == 3.
    """
    from server import index_folder, find_no_subject

    index_folder(str(jpg_dir))
    result = find_no_subject(str(jpg_dir), limit=1)

    assert result["count"] == 3
    assert len(result["results"]) == 1


def test_find_no_subject_count_only(jpg_dir):
    """
    find_no_subject with count_only=True must return only count and folder.

    Indexes 3 photos, then queries with count_only=True.
    Confirms response has no "results" key (no row payload).

    Expected output: dict with "count" and "folder", no "results" key.
    """
    from server import index_folder, find_no_subject

    index_folder(str(jpg_dir))
    result = find_no_subject(str(jpg_dir), count_only=True)

    assert result["count"] == 3
    assert result["folder"] == str(jpg_dir)
    assert "results" not in result


# ---------------------------------------------------------------------------
# find_unsharp_subjects tests
# ---------------------------------------------------------------------------

def test_find_unsharp_subjects_with_limit(jpg_dir):
    """
    find_unsharp_subjects must respect limit parameter.

    Indexes 3 photos (all unscoreable faces = fallback_used=True, no eye sharpness).
    Queries relative mode with limit=1.
    Confirms only 1 result despite 3 photos in cache.

    Expected output: results list has max length 1.
    """
    from server import index_folder, find_unsharp_subjects

    index_folder(str(jpg_dir))
    result = find_unsharp_subjects(str(jpg_dir), limit=1)

    assert "results" in result
    assert len(result["results"]) <= 1


def test_find_unsharp_subjects_count_only(jpg_dir):
    """
    find_unsharp_subjects with count_only=True must return only count and folder.

    Indexes 3 photos, then queries with count_only=True.
    Confirms response has no "results" key.

    Expected output: dict with "count" and "folder", no "results" key.
    """
    from server import index_folder, find_unsharp_subjects

    index_folder(str(jpg_dir))
    result = find_unsharp_subjects(str(jpg_dir), count_only=True)

    assert "count" in result
    assert result["folder"] == str(jpg_dir)
    assert "results" not in result
